name: Actualitza EPG

on:
  schedule:
    # S'executa automàticament cada 6 hores (a les 00:00, 06:00, 12:00 i 18:00 UTC)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Permet executar el workflow manualment des de la pestanya Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar el repositori
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Instal·lar dependències
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generar EPG
      run: python scripts/generate_epg.py

    - name: Desar canvis a GitHub
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add epg.xml
        git commit -m "Auto-update EPG data" || exit 0
        git push
